### ISSUE TITLE
猎聘投递问题，发现猎聘没办法自动打招呼，并附上解决方案

### ISSUE THREAD

**Issue by lj2508-com** [loks666/get_jobs#16]
今天用猎聘投递的时候，发现一直在显示投递整页，但是发现没有打招呼，简单看了下代码，发现应该是按钮点击事件有问题，
不知道是不是网页渲染问题，我这把需要修改后才能成功。可能是猎聘有所调整，也可以在异常捕捉到之后，增加一个备用选项

原代码
  button = CHROME_DRIVER.findElement(By.xpath("//button[@class='ant-btn ant-btn-primary ant-btn-round']"));
将115行代码修改如下
  button = CHROME_DRIVER.findElement(By.xpath("//button[@class='ant-btn ant-btn-round ant-btn-primary']"));

**Comment by loks666** [comment]
提个pr到dev，我测一下

**Comment by lj2508-com** [comment]
> 提个pr到dev，我测一下
好久没上GitHub了，抱歉，已经提交pr，还修复了一下谷歌浏览器兼容的问题，您看一下

**Comment by loks666** [comment]
你的那个依赖问题很大，我全都删了，因为你这个代码如果合并了，影响的人实在太多了，我都回退了

**Comment by loks666** [comment]
猎聘有段时间是没有页码的，现在他们又把页面加回来了，后面我看下我来修改吧
