### ISSUE TITLE
智联报错

### ISSUE THREAD

**Issue by anwenmp** [loks666/get_jobs#29]
![image](https://github.com/user-attachments/assets/3775eede-fcea-4b52-b607-cb85fa890a71)

**Comment by fuguiKz** [comment]
+1

**Comment by loks666** [comment]
已解决，如果更新后还是报错，说明是你自己电脑的分辨率不匹配，请自行调试代码

**Comment by anwenmp** [comment]
@loks666 猎聘多支持点城市呗，比如天津

**Comment by loks666** [comment]
你们可以把想加的城市代码发给我，然后我统一加，城市太多了，我不可能自己手动一个一个找

**Comment by anwenmp** [comment]
@loks666 天津的城市代码：030
