### ISSUE TITLE
发送不了消息

### ISSUE THREAD

**Issue by AnderChris** [loks666/get_jobs#3]
佬，我投递boss的时候它没办法发送预设好的消息

**Comment by loks666** [comment]
这是你的页面和我的不用，你需要排除哪个元素选中失败的

**Comment by loks666** [comment]
> 佬，我投递boss的时候它没办法发送预设好的消息

今天解决了一个问题，boss投递必须要关闭自动打招呼，我觉得你可能是这个原因
