### ISSUE TITLE
黑名单机制问题

### ISSUE THREAD

**Issue by loshine** [loks666/get_jobs#32]
您好，目前使用该项目求职中，发现黑名单里有一部分是本人发出的信息里有「感谢」、「谢谢」导致公司被拉黑名单了，请问黑名单是从信息里读取到 「感谢」、「谢谢」之类的词来拉的吗？这个是不是应该要检测一下是否是本人发出的消息来避免这种情况

多谢。

**Comment by loks666** [comment]
是的，黑名单就是检测消息中是否包含谢谢之类的词语更新黑名单的，不应该检测是否本人发出的消息，因为没什么用
