### ISSUE TITLE
BOSS报错--无法找到.env

### ISSUE THREAD

**Issue by LooooghanWang** [loks666/get_jobs#35]
![image](https://github.com/user-attachments/assets/ec1cb1e4-62ad-4132-83bf-3c09781148e7)

**Comment by LooooghanWang** [comment]
其它平台都可以正常投递，BOSS报错

**Comment by silent-wind1** [comment]
你没有看文档吧，文档写了把一个文件后缀改成.env

**Comment by loks666** [comment]
别人说的没错，自己没有看文档提这些没有意义的问题，没有什么用
