### ISSUE TITLE
请求添加Bark推送通知支持

### ISSUE THREAD

**Issue by Mikihta** [loks666/get_jobs#38]
你好，

我想建议在项目中添加对[Bark](https://bark.day.app/)推送通知的支持。Bark是iOS平台一个可靠且可定制的移动设备推送通知服务，能够让用户方便地接收通知。将其添加到项目中，可以为用户提供更多的通知方式，增强项目的灵活性。

相关文档:
有关配置和集成的详细信息，请参考Bark的官方文档：[bark.day.app](https://bark.day.app/)。

功能请求:

添加Bark推送通知的配置选项。
提供通过Bark API发送通知的相关设置。
理由:
集成Bark推送通知将为依赖此服务的用户提供一个额外的通知渠道，从而提高项目的可用性和灵活性。

感谢考虑此功能请求，期待在项目中看到Bark推送的支持！

**Comment by loks666** [comment]
此项功能会增加系统复杂度，且实际意义不大，如果定制开发可以考虑，在发布版本不会考虑此项功能的开发
